version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sushi_express_db
    environment:
      POSTGRES_DB: sushi_express
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: sushi_express_backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/sushi_express
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - JWT_SECRET_KEY=your-jwt-secret-key-change-this-in-production
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
